spring:
  datasource:
    url: jdbc:h2:mem:passport
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

ember:
  api:
    base-url: https://api.ember.to